name: build and publish polygons to data.artsdatabanken.no

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present
      - name: Run deployment script
        run: ./.github/workflows/deploy.sh 
        shell: bash
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "naturvern/*"
          tag: v_${{ github.run_number }}
      - name: post to slack
        run: ./.github/workflows/slack.sh ${{ secrets.POST_SLACK }}
        shell: bash
      - uses: actions/checkout@v3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: artsdatabanken/naturvern-kart
          path: './destinationRepo'
      - name: Copy files to destinationRepo
        run: | 
            echo "Where are we?"
            ls -l 
            cp build/polygon_med_undertyper.25833.geojson destinationRepo/
            cp build/polygon_med_undertyper.4326.geojson destinationRepo/
            cp build/kildedata.4326.geojsonl destinationRepo/