name: build and publish polygons to data.artsdatabanken.no

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install sshpass
        run: sudo apt-get install -y sshpass
      - run: npm ci
      - run: npm run build --if-present
      - name: Run deployment script
        run: ./.github/workflows/deploy.sh 
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: naturvern
          path: naturvern
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "naturvern/*"
      - name: Slackit
        run: curl -X POST -H 'Content-type: application/json' --data '{"text":"deploy naturvern-kart-lastejobb"}' ${{ secrets.POST_SLACK }}
